/*
 *   Project: Speedith
 * 
 * File name: TextSDInputDialog.java
 *    Author: Matej Urbas [matej.urbas@gmail.com]
 * 
 *  Copyright © 2012 Matej Urbas
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package speedith.ui.input;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.prefs.Preferences;
import javax.swing.DefaultListModel;
import speedith.core.lang.SpiderDiagram;
import speedith.core.lang.reader.SpiderDiagramsReader;
import speedith.i18n.Translations;
import static speedith.i18n.Translations.*;

/**
 *
 * @author Matej Urbas [matej.urbas@gmail.com]
 */
public class TextSDInputDialog extends javax.swing.JDialog {

    // <editor-fold defaultstate="collapsed" desc="Fields">
    private boolean cancelled = true;
    private SpiderDiagram spiderDiagram = null;
    private DefaultListModel<String> storedSDs;
    // </editor-fold>

    /**
     * Creates new form TextSDInputDialog
     */
    public TextSDInputDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInputText = new javax.swing.JLabel();
        spInputText = new javax.swing.JScrollPane();
        taInputText = new javax.swing.JTextArea();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstStoredSDs = new javax.swing.JList();
        btnStore = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("speedith/i18n/strings"); // NOI18N
        setTitle(bundle.getString("TEXT_INPUT_DIALOG_TITLE")); // NOI18N

        lblInputText.setText(bundle.getString("TEXT_INPUT_DIALOG_LBL_INPUT")); // NOI18N

        taInputText.setColumns(20);
        taInputText.setRows(5);
        taInputText.setTabSize(4);
        spInputText.setViewportView(taInputText);

        btnOk.setMnemonic(java.util.ResourceBundle.getBundle("speedith/i18n/strings").getString("TEXT_INPUT_DIALOG_OK_MNEMONIC").charAt(0));
        btnOk.setText(bundle.getString("TEXT_INPUT_DIALOG_OK")); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setMnemonic(java.util.ResourceBundle.getBundle("speedith/i18n/strings").getString("TEXT_INPUT_DIALOG_CANCEL_MNEMONIC").charAt(0));
        btnCancel.setText(bundle.getString("TEXT_INPUT_DIALOG_CANCEL")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblErrorMessage.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        lblErrorMessage.setForeground(new java.awt.Color(204, 0, 0));

        lstStoredSDs.setModel(this.getStoredSDList());
        lstStoredSDs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstStoredSDs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onItemClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstStoredSDs);

        btnStore.setMnemonic(i18n("TEXT_INPUT_DIALOG_STORE_MNEMONIC").charAt(0));
        btnStore.setText(i18n("TEXT_INPUT_DIALOG_STORE")); // NOI18N
        btnStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onStoreSD(evt);
            }
        });

        btnDelete.setMnemonic(i18n("TEXT_INPUT_DIALOG_DELETE_MNEMONIC").charAt(0));
        btnDelete.setText(i18n("TEXT_INPUT_DIALOG_DELETE")); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDeleteSD(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                        .addGap(66, 66, 66)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOk))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInputText)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spInputText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnStore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInputText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spInputText, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel)
                    .addComponent(lblErrorMessage))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        String sdText = taInputText.getText();
        try {
            spiderDiagram = SpiderDiagramsReader.readSpiderDiagram(sdText);
            cancelled = false;
            dispose();
        } catch (Exception ex) {
            lblErrorMessage.setText(Translations.i18n("TEXT_INPUT_DIALOG_INVALID_SD_TEXT", ex.getLocalizedMessage()));
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void onStoreSD(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onStoreSD
        String sd = taInputText.getText();
        storedSDs.addElement(sd);
        storeCurrentSDs();
    }//GEN-LAST:event_onStoreSD

    private void onDeleteSD(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDeleteSD
        if (!lstStoredSDs.getSelectionModel().isSelectionEmpty()) {
            storedSDs.removeElementAt(lstStoredSDs.getSelectedIndex());
            storeCurrentSDs();
        }
    }//GEN-LAST:event_onDeleteSD

    private void onItemClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onItemClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            if (!lstStoredSDs.getSelectionModel().isSelectionEmpty()) {
                taInputText.setText(storedSDs.elementAt(lstStoredSDs.getSelectedIndex()));
            }
        }
    }//GEN-LAST:event_onItemClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextSDInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextSDInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextSDInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextSDInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TextSDInputDialog dialog = new TextSDInputDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnStore;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblInputText;
    private javax.swing.JList lstStoredSDs;
    private javax.swing.JScrollPane spInputText;
    private javax.swing.JTextArea taInputText;
    // End of variables declaration//GEN-END:variables

    /**
     * Indicates whether the user pressed the cancel button.
     *
     * <p>If this method returns {@code false} then a valid spider diagram will
     * be set in {@link TextSDInputDialog#getSpiderDiagram()}.</p>
     *
     * @return a value that indicates whether the user pressed the cancel
     * button.
     */
    public boolean isCancelled() {
        return cancelled;
    }

    /**
     * The spider diagram that will be converted to text and which in turn will
     * be passed to {@link TextSDInputDialog#setSpiderDiagramText(java.lang.String)
     * }.
     *
     * @param sd the spider diagram that will be converted to text and which in
     * turn will be passed to {@link TextSDInputDialog#setSpiderDiagramText(java.lang.String)
     * }.
     */
    public void setSpiderDiagramText(SpiderDiagram sd) {
        if (sd == null) {
            setSpiderDiagramText("");
        } else {
            setSpiderDiagramText(sd.toString());
        }
    }

    /**
     * Sets the text that will be displayed in the central text area of this
     * dialog. This text represents the user's input spider diagram.
     *
     * @param text the text that will be displayed in the central text area of
     * this dialog.
     */
    public void setSpiderDiagramText(String text) {
        taInputText.setText(text);
    }

    /**
     * Returns the spider diagram as represented by the text at the time when
     * the user pressed the 'Okay' button.
     *
     * @return the spider diagram as represented by the text at the time when
     * the user pressed the 'Okay' button.
     */
    public SpiderDiagram getSpiderDiagram() {
        return spiderDiagram;
    }
    private static final String StoredSDsPrefKey = "stored-input-sds";

    public static void storeSpiderDiagrams(List<String> sds) {
        Preferences prefs = Preferences.userNodeForPackage(TextSDInputDialog.class);
        for (int i = 0; i < sds.size(); i++) {
            String sd = sds.get(i);
            prefs.put(getStoredSDPrefKey(i), sd == null ? "" : sd);
        }
        prefs.remove(getStoredSDPrefKey(sds.size()));
    }

    public static List<String> loadSpiderDiagrams() {
        Preferences prefs = Preferences.userNodeForPackage(TextSDInputDialog.class);

        ArrayList<String> sds = new ArrayList<>();

        for (int i = 0; true; i++) {
            String sd = prefs.get(getStoredSDPrefKey(i), null);
            if (sd == null) {
                break;
            } else {
                sds.add(sd);
            }
        }

        return sds;
    }

    private static String getStoredSDPrefKey(int idx) {
        return StoredSDsPrefKey + "-" + Integer.toString(idx);
    }

    private DefaultListModel<String> getStoredSDList() {
        storedSDs = new DefaultListModel<>();
        List<String> sds = loadSpiderDiagrams();
        for (String sd : sds) {
            storedSDs.addElement(sd);
        }
        return storedSDs;
    }

    private void storeCurrentSDs() {
        if (storedSDs != null) {
            ArrayList<String> sds = new ArrayList<>();
            for (int i = 0; i < storedSDs.size(); i++) {
                sds.add(storedSDs.elementAt(i));
            }
            storeSpiderDiagrams(sds);
        }
    }
}
