#! /bin/bash

mvn install:install-file \
  -Dfile=libinkml/inkmllibj.jar \
  -DgroupId=inkmllibj \
  -DartifactId=inkmllibj \
  -Dversion=0.0.1 \
  -Dpackaging=jar \
  -DgeneratePom=true

mvn install:install-file \
  -Dfile=recognizer/recognizer.jar \
  -DgroupId=recognizer \
  -DartifactId=recognizer \
  -Dversion=0.0.1 \
  -Dpackaging=jar \
  -DgeneratePom=true